version: "3.9"

services:
  front:
    container_name: front
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - front_vol:/front/my-app
      # - ${PWD}/data:/front/my-app
    env_file:
      - .env

volumes:
  front_vol:
    driver_opts:
      type: none
      device: ${PWD}/srcs/front/my-app
      # device: ./front/my-app
      o: bind
